In [20]:
import numpy as np
from scipy.linalg import fractional_matrix_power

In [21]:
ins = open( "D:\\Kortunov\\transfer\\Hyagda\\temp_ini.3DArray", "r" )

In [22]:
#lines_after_2 = ins.readlines()[2:]

In [23]:
data = []
summ = 0
lines_after_2 = ins.readlines()[2:]
for a in range(1,11):
    print(a)
    lines_after = []
    lines_after =lines_after_2[a*421-421:a*421].copy()
    lines_after = lines_after[1:]
#    lines_after = lines_after[a:]
    for line in lines_after:
        number_strings = line.split() # Split the line on runs of whitespace
        numbers = [float(n) for n in number_strings]
#    print(numbers)
        data.append(numbers) # Add the "row" to your list.
        summ = summ + 1
summ

1
2
3
4
5
6
7
8
9
10


4200

In [25]:
a = np.array(data)
a = np.absolute(a)
array_sum = np.sum(a)
array_has_nan = np.isnan(array_sum)

print(array_has_nan)


False


In [26]:
A_1 = 1e-03
A_2 = 1
A_3 = 1.5512e-02
A_4 = -20
A_5 = -1.572
mu0 = 0.001303401

In [27]:
visc = a+A_4
visc = visc*A_3
visc  = visc+A_2
visc  = visc.astype(float)**float(A_5)
visc  = visc*A_1
visc = mu0/visc
visc[visc > 10000] = -1e+20

In [28]:
np.savetxt('D:\\Kortunov\\transfer\\Hyagda\\test_vova_out.3DArray',visc)

In [29]:
f = open('D:\\Kortunov\\transfer\\Hyagda\\test_vova_out.3DArray', "r")
contents = f.readlines()
f.close()
summ = 0
for a in range(1,11):
    print(a)
    contents.insert(summ,'INTERNAL 1 (FREE) -1\n')
    summ = summ+421
f = open('D:\\Kortunov\\transfer\\Hyagda\\test_vova_out.3DArray', "w")
contents = "".join(contents)
f.write(contents)
f.close()

1
2
3
4
5
6
7
8
9
10


In [30]:
f = open('D:\\Kortunov\\transfer\\Hyagda\\test_vova_out.3DArray', "r")
contents = f.readlines()
f.close()

contents.insert(0,'340,420,10 -- NCOL NROW NLAY\n')

f = open('D:\\Kortunov\\transfer\\Hyagda\\test_vova_out.3DArray', "w")
contents = "".join(contents)
f.write(contents)
f.close()

In [31]:
f = open('D:\\Kortunov\\transfer\\Hyagda\\test_vova_out.3DArray', "r")
contents = f.readlines()
f.close()

contents.insert(0,'#3DMODFLOWARRAY\n')

f = open('D:\\Kortunov\\transfer\\Hyagda\\test_vova_out.3DArray', "w")
contents = "".join(contents)
f.write(contents)
f.close()

In [321]:
visc

array([], dtype=float64)

In [232]:
a = np.array([7.05E-01])
a

array([0.705])

In [192]:
float(a)**float(A_5)

(-9.299760193952932e-21+3.0216752572580636e-21j)

In [234]:
a.astype(float)**-1.572

array([1.73239415])

In [216]:
a

array([-1.5512e+18])